# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://abba01001.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# highlight:
#   enable: false
# prism_plugin:
#   mode: 'preprocess'    # realtime/preprocess
#   theme: 'tomorrow'
#   line_number: false    # default false
#   custom_css:

syntax_highlighter: prismjs
highlight:
  enable: false
prism_plugin:
  enable: true
  mode: 'preprocess'
  #auto_detect : true
  theme: 'okaidia'
  line_number: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/abba01001/abba01001.github.io
  branch: main

#搜索
search:
  path: search.xml
  field: post

#中文链接转拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

#文章字数统计插件
postInfo:
  date: true
  update: false
  wordCount: false # 设置文章字数统计为 true.
  totalCount: false # 设置站点文章总字数统计为 true.
  min2read: false # 阅读时长.
  readCount: false # 阅读次数.

#添加emoji表情支持
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:


OhMyLive2d:
  enable: true
  CDN: https://unpkg.com/oh-my-live2d
  option:
    menus:
      disable: true, # 禁用右键菜单
    dockedPosition: 'right' # 模型停靠位置 默认值: 'right' 可选值: 'left' | 'right'
    mobileDisplay: true # 是否在移动端显示
    restMessage: '' # 模型休息时的消息
    tips:
      copyTips:
        duration: 3000
        message:
          - '你复制了什么内容呢?记得注明出处哦~'
      idleTips:
        duration: 5000 # 持续时间（单位：毫秒）
        interval: 60000 # 闲置提示间隔时间（单位：毫秒）
        message:
          - '欢迎来到我的小站~'
          - '在忙吗？'
          - '有任何问题，可以问我~'
      welcomeTips:
        duration: 6000 # 欢迎提示持续时间（单位：毫秒）
        message.afternoon:
          - '午后很容易犯困呢~'
        message.daybreak:
          - '早上好呀，新的一天又开始了~'
        message.dawn:
          - '早上好呀，新的一天又开始了~'
        message.evening:
          - '晚上好呀，今天过得怎么样~'
      mobileStyle:
        width: 150
        height: 80
        left: calc(50% - 10px)  # 居中显示
        top: -100px
        background-color: rgba(0, 0, 0, 0.8)  # 深色背景，透明度调整
        color: rgba(0, 255, 255, 1)
        font-size: 16px
        font-weight: bold  # 加粗字体，增加可读性
        text-align: center  # 文本居中
        border-radius: 25px  # 圆角
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3)  # 阴影效果
        padding: 8px
        backdrop-filter: blur(3px)  # 背景模糊效果
        text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3)  # 字体阴影，增强对比度
      style:
        width: 230
        height: 120
        left: calc(50% - 0px)  # 居中显示
        top: -100px
        background-color: rgba(0, 0, 0, 0.8)  # 深色背景，透明度调整
        color: rgba(0, 255, 255, 1)
        font-size: 16px
        font-weight: bold  # 加粗字体，增加可读性
        text-align: center  # 文本居中
        border-radius: 25px  # 圆角
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3)  # 阴影效果
        padding: 8px
        backdrop-filter: blur(3px)  # 背景模糊效果
        text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3)  # 字体阴影，增强对比度
    models:
      - path: /live2d-models/mark_free_zh/runtime/mark_free_t04.model3.json
        position: [-65, -40] # 模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
        scale: 0.15 # 模型的缩放比例 默认值: 0.1
        stageStyle:
          width: 250
          height: 270
        mobilePosition: [-65, -40] # 移动端时模型在舞台中的位置
        mobileScale: 0.1 # 移动端时模型的缩放比例
        mobileStageStyle: # 移动端时舞台的样式
          width: 150
          height: 170
        motionPreloadStrategy: ALL # 动作预加载策略 默认值: IDLE 可选值: ALL | IDLE | NONE
    # 通用样式设置
    parentElement: document.body # 为组件提供一个父元素，如果未指定则默认挂载到 body 中
    primaryColor: 'var(--btn-bg)' # 主题色 支持 CSS 变量